version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
  post_build:nvgvhgv
    commands:
      - echo Build completed on `date`
      - tar -cvzf riches.tgz .
artifacts:
  files:
    - riches.tgz
    
    
    
    
